CREATE TABLE FILM(
   film_no			INT		NOT NULL,
   film_name		TEXT,
   review_no		INT		NOT NULL,
   review_title		TEXT,
   review_time		TEXT,
   star				INT,
   views			INT,
   yakutachido		INT,
   review_text		TEXT,
   monogatari_star	INT,
   haiyaku_star		INT,
   enshutu_star		INT,
   eizou_star		INT,
   onngaku_star		INT,
   imageword1		TEXT,
   imageword2		TEXT,
   imageword3		TEXT,
   imageword4		TEXT,
   imageword5		TEXT,
   imageword6		TEXT,
   imageword7		TEXT,
   imageword8		TEXT,
   imageword9		TEXT,
   imageword10		TEXT,
   imageword11		TEXT,
   imageword12		TEXT,
   imageword13		TEXT,
   imageword14		TEXT,
   imageword15		TEXT,
   imageword16		TEXT,
   imageword17		TEXT,
   imageword18		TEXT,
   imageword19		TEXT,
   imageword20		TEXT,
   constraint pk_FILM primary key (film_no,review_no)
);